name: musicapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Bloc
  flutter_bloc:
  equatable:
  # Firebase
  firebase_auth:
  firebase_core:
  cloud_firestore:
  google_sign_in: ^5.3.0
  flutterfire_ui: ^0.4.0+2
  # Frontend
  record: ^3.0.4
  avatar_glow: ^2.0.2
  url_launcher: ^6.0.20
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
